main: com.github.Dewynion.embercore.EmberCore
name: EmberCore
author: dewynion
version: 0.7.0
api-version: 1.16
load: STARTUP
description: Library containing methods to assist with reflection, physics, geometry, and more.
commands:
  shape:
    description: Testing command. Generates a particle shape where the player is looking.
    usage: /<command>
    default: true
  menutest:
    description: Testing command. Opens a multi-page menu with random items in it.
    usage: /<command>
    default: true
  nmstest:
    description: Testing command. Logs some NMS-related stuff to console. Most people won't need this at all.
    usage: /<command>
    default: true
