main: com.github.Dewynion.embercore.EmberCore
name: Embercore
author: dewyn
version: 1.1.0
api-version: 1.16
load: STARTUP
description: Multipurpose library designed to streamline plugin development and reduce boilerplate code.
website: https://github.com/Blu-Fantasy-Online/EmberCore/