main: com.github.Dewynion.embercore.EmberCore
name: EmberCore
author: dewynion
version: 0.8.2
api-version: 1.16
load: STARTUP
description: Library containing methods to assist with reflection, physics, geometry, and more.
website: https://github.com/Dewynion/EmberCore/